volumes:
  mongo_data:

services:
  app:
    image: pun0205/midterm-devops-app:phase3 
    container_name: app
    ports:
      - "3000:3000"
    env_file:
      - ../.env
    volumes:
      - type: bind
        source: /opt/app/uploads
        target: /app/uploads
    depends_on:
      mongo:
        condition: service_healthy
    restart: unless-stopped

  mongo:
    image: mongo:6
    container_name: mongo
    volumes:
      - type: volume
        source: mongo_data
        target: /data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
