volumes:
  mongo_data:
  uploads_data:
  caddy_data:
  caddy_config:

services:
  app:
    image: pun0205/midterm-devops-app:phase3
    container_name: app
    ports:
      - "3000:3000"
    env_file:
      - ../.env
    volumes:
      - type: volume
        source: uploads_data
        target: /app/uploads
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:6
    container_name: mongo
    volumes:
      - type: volume
        source: mongo_data
        target: /data/db
    restart: unless-stopped

  caddy:
    image: caddy:2
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app
    restart: unless-stopped
